# Use root/example as user/password credentials
version: '3.1'

services:
  mariadb:
    image: linuxserver/mariadb:alpine
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
    ports:
      - 3306:3306
    volumes:
      - '/home/pi/Documents/BinanceSupervision/DB/:/var/lib/mysql'
    container_name: mariadb

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    links:
      - "mariadb:db"
    container_name: myadmin
