# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Resource_BinanceSupervision_main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(827, 578)
        MainWindow.setIconSize(QtCore.QSize(100, 100))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_BinanceState = QtWidgets.QLabel(self.centralwidget)
        self.label_BinanceState.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_BinanceState.setObjectName("label_BinanceState")
        self.gridLayout.addWidget(self.label_BinanceState, 1, 1, 1, 1)
        self.mainTab = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTab.setAutoFillBackground(False)
        self.mainTab.setObjectName("mainTab")
        self.CryptoBalance = QtWidgets.QWidget()
        self.CryptoBalance.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CryptoBalance.setObjectName("CryptoBalance")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.CryptoBalance)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableView = QtWidgets.QTableView(self.CryptoBalance)
        self.tableView.setObjectName("tableView")
        self.gridLayout_2.addWidget(self.tableView, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.mainTab.addTab(self.CryptoBalance, "")
        self.FiscalBalance = QtWidgets.QWidget()
        self.FiscalBalance.setObjectName("FiscalBalance")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.FiscalBalance)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.FiscalBalance)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.FiscalBalance)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.mainTab.addTab(self.FiscalBalance, "")
        self.TransactionHistory = QtWidgets.QWidget()
        self.TransactionHistory.setObjectName("TransactionHistory")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.TransactionHistory)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.le_PathFile = QtWidgets.QLineEdit(self.TransactionHistory)
        self.le_PathFile.setObjectName("le_PathFile")
        self.gridLayout_6.addWidget(self.le_PathFile, 0, 1, 1, 1)
        self.btn_AnalyzeFile = QtWidgets.QPushButton(self.TransactionHistory)
        self.btn_AnalyzeFile.setObjectName("btn_AnalyzeFile")
        self.gridLayout_6.addWidget(self.btn_AnalyzeFile, 2, 2, 1, 1)
        self.lb_loadFile = QtWidgets.QLabel(self.TransactionHistory)
        self.lb_loadFile.setObjectName("lb_loadFile")
        self.gridLayout_6.addWidget(self.lb_loadFile, 0, 0, 1, 1)
        self.btn_LoadFile = QtWidgets.QPushButton(self.TransactionHistory)
        self.btn_LoadFile.setObjectName("btn_LoadFile")
        self.gridLayout_6.addWidget(self.btn_LoadFile, 0, 2, 1, 1)
        self.btn_parseFile = QtWidgets.QPushButton(self.TransactionHistory)
        self.btn_parseFile.setObjectName("btn_parseFile")
        self.gridLayout_6.addWidget(self.btn_parseFile, 1, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.TransactionHistory)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_6.addWidget(self.line, 3, 0, 1, 3)
        self.widget = QtWidgets.QWidget(self.TransactionHistory)
        self.widget.setObjectName("widget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 682, 331))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_10.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_10.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_10.addWidget(self.label_10, 4, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.gridLayout_10.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.gridLayout_10.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_9.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget, 4, 0, 1, 2)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.mainTab.addTab(self.TransactionHistory, "")
        self.gridLayout.addWidget(self.mainTab, 0, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 827, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../models/images/information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon)
        self.actionAbout.setObjectName("actionAbout")
        self.action_New = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\images/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_New.setIcon(icon1)
        self.action_New.setObjectName("action_New")
        self.action_Connect = QtWidgets.QAction(MainWindow)
        self.action_Connect.setObjectName("action_Connect")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Disconnect = QtWidgets.QAction(MainWindow)
        self.action_Disconnect.setObjectName("action_Disconnect")
        self.menu_File.addAction(self.action_Connect)
        self.menu_File.addAction(self.action_Disconnect)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_New)
        self.menu_File.addAction(self.action_Exit)
        self.menu_Help.addAction(self.actionAbout)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.mainTab.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Binance Supervision"))
        self.label_BinanceState.setText(_translate("MainWindow", "Binance disconnected"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.CryptoBalance), _translate("MainWindow", "Crypto Balance"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.FiscalBalance), _translate("MainWindow", "Fiscal Balance"))
        self.btn_AnalyzeFile.setText(_translate("MainWindow", "Analyze"))
        self.lb_loadFile.setText(_translate("MainWindow", "File to load:"))
        self.btn_LoadFile.setText(_translate("MainWindow", "Load"))
        self.btn_parseFile.setText(_translate("MainWindow", "Parse File"))
        self.label_9.setText(_translate("MainWindow", "Total invested :"))
        self.label_8.setText(_translate("MainWindow", "Asset Symbol"))
        self.label_10.setText(_translate("MainWindow", "Average Price at buy :"))
        self.groupBox.setTitle(_translate("MainWindow", "AssetSymbol"))
        self.label_4.setText(_translate("MainWindow", "Average Price at buy :"))
        self.label_11.setText(_translate("MainWindow", "Total invested : "))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_7.setText(_translate("MainWindow", "Average Price at buy :"))
        self.label_6.setText(_translate("MainWindow", "Total invested :"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.TransactionHistory), _translate("MainWindow", "Transaction History"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.action_New.setText(_translate("MainWindow", "&New"))
        self.action_New.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_Connect.setText(_translate("MainWindow", "&Connect"))
        self.action_Exit.setText(_translate("MainWindow", "&Exit"))
        self.action_Disconnect.setText(_translate("MainWindow", "Disconnect"))
